### ISSUE TITLE
Adress-book not displayed on Check-out

### ISSUE THREAD

**Issue by UbiConcept** [hallme/woo-address-book#84] opened 2020-08-18 21:21 UTC
What should i look for to fix?

**Comment by matt-h** [comment] 2020-08-19 18:40
Do you have anything that customizes the checkout fields in any way? It is possible that something that modifies the shipping fields is removing the address book field.

The address book field also does not display unless you have at least one shipping address saved to your profile.

**Comment by UbiConcept** [comment] 2020-08-19 19:48
I disabled everything, to see and still not showing(with 3 addresses)

Envoyé de mon iPhone

Le 19 août 2020 à 14:40, Matt <notifications@github.com> a écrit :

﻿

Do you have anything that customizes the checkout fields in any way? It is possible that something that modifies the shipping fields is removing the address book field.

The address book field also does not display unless you have at least one shipping address saved to your profile.

**Comment by UbiConcept** [comment] 2020-08-19 19:49
Site is in French, could that impact in any way, not standard woocomerce names for pages etc

Envoyé de mon iPhone

Le 19 août 2020 à 14:40, Matt <notifications@github.com> a écrit :

﻿

Do you have anything that customizes the checkout fields in any way? It is possible that something that modifies the shipping fields is removing the address book field.

The address book field also does not display unless you have at least one shipping address saved to your profile.

**Comment by matt-h** [comment] 2020-08-19 20:49
Language shouldn't matter, it ties all into core WooCommerce address fields. I could take a look if you are able to share the site. If you don't want to post it publicly here, you can email me at matt@hallme.com

**Comment by inf3cti0n95** [comment] 2021-01-10 05:36
@matt-h I'm having the same problem, it's not showing multiple addresses to select from in the checkout page

**Comment by matt-h** [comment] 2021-01-11 02:05
@inf3cti0n95 do you have any other details to go on in order to reproduce the issue? It works fine in all of our tests and on our demo site at https://woo-address-book.hallme.com/

**Comment by matt-h** [comment] 2021-05-07 15:16
Closing due to no reply. If anyone has any details on how to reproduce this then feel free to reply still.

**Closed by matt-h** 2021-05-07 15:16 UTC
Labels: question
