### ISSUE TITLE
Provinces/States not switching when country is changes

### ISSUE THREAD

**Issue by joongpark** [hallme/woo-address-book#44] opened 2019-04-23 13:34 UTC
My woocommerce default is set to Canada.
When trying to add additional address, provinces do not change to states when country is changed. I only see Canadian provinces even when country is changed to USA.

**Comment by matt-h** [comment] 2019-04-30 18:14
Hi @joongpark Thank you for the report here. This should be fixed in our newly released version 1.5.0 of the plugin.
Let us know if you are still having any issues after updating.

**Closed by matt-h** 2019-04-30 18:14 UTC

**Comment by joongpark** [comment] 2019-04-30 18:32
Thank you.
I do not see your new update being pushed out. I do not see "Update" on my plug-in page. I see my current version is 1.4.1

Do everyone lose their address book if I delete the plug-in and re-install 1.5.0?

Thanks.

**Comment by matt-h** [comment] 2019-04-30 19:13
It shows updated on WordPress.org https://wordpress.org/plugins/woo-address-book/

You might just need to check for updates under "Dashboard" => "Updates" => "Check Again"

If you delete the plugin, addresses are not lost once you re install it.

**Comment by joongpark** [comment] 2019-04-30 19:17
Update was pushed to us as 1.5.1 just now. Thank you.

**Comment by joongpark** [comment] 2019-04-30 19:20
I just updated to 1.5.1 but issue still persists. I changed country to other countries but province/state does not update to the chosen country.

**Comment by matt-h** [comment] 2019-04-30 19:47
I'm not sure, I can change between US and Canada as well as other countries just fine and the fields update approprotely.

I have tested on the Edit Address pages for multiple addresses and the add new address as well as the shipping address on the checkout page.

It is possible there is a conflict with another plugin that you have or a setting in your WooCommerce setup or theme.

A few things to check to help us pinpoint what is going on:
  * Does it also happen when editing the default shipping address? ( `/my-account/edit-address/shipping/` )
  * If so, does it also happen there with the Address Book plugin disabled?
    * If it still does then it is not something with the Address Book plugin.
  * What other plugins are you using?
     * You can get a full status report of your site by going to WooCommerce -> Status -> Get system report and copying the info from there.

If we still don't get anywhere an example site where you are having the issue could help.

Feel free to email me at matt@hallme.com with any info that you don't want to include on github.

**Comment by joongpark** [comment] 2019-04-30 20:08
Here is what I found out.

If original (first) shipping address in US then additional address loads US states when adding/editing. States can only be changed if I change country to Canada and try to save. It will save country and give error saying province is wrong. Reloaded will page now have provinces to select.

It's exact same issue as this but it shows fixed but not for me. I am running latest Wordpress/woocommerce

**Comment by matt-h** [comment] 2019-05-01 19:30
Hi, I'm still not able to reproduce this issue.

If you could provide a login on a site or a sandbox site where this is happening, I can take a further look.
